name: .NET

on:
  workflow_call:
    inputs:
      BUILD_TARGET:
        required: true
        type: string

env:
  config: Release
  disable_test_parallelization: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Run Tests
        env:
          BUILD_TARGET: ${{ inputs.BUILD_TARGET }}
        run: ./build.sh $BUILD_TARGET

      - name: Stop containers
        if: always()
        run: docker compose down
